version: "3"

services:
  # MariaDB Setup
  db:
    image: mariadb:10.5
    # Importante para fazer a conexao com a db!
    # Coloque como host a mesma coisa
    # que o container_name!
    container_name: "mariadb-server"
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=my_database
    ports:
      - 8011:3306
    volumes:
      - ./.docker/db:/var/lib/mysql
      - ./db:/db

  # Build do PHP separada do Nginx
  # para trocar a versao do php mude no .docker/php/Dockerfile
  php:
    build: .docker/php
    container_name: "php-server"
    image: server-php-nginx
    volumes:
      - ./www/:/var/www/html
    ports:
      - "9000:9000"

  # Build do Nginx preparada para PHP
  nginx:
    image: nginx
    container_name: "nginx-server"
    volumes:
      # enable SSL
      - .docker/nginx/server.pem:/etc/nginx/ssl/server.pem
      - .docker/nginx/server-key.pem:/etc/nginx/ssl/server-key.pem
      # Ngixn configs
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      # logs
      - .docker/nginx/client-access.log:/var/log/nginx/client-access.log;
      - .docker/nginx/client-error.log:/var/log/nginx/client-error.log;
      # Server root
      - ./www/:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    links:
      - db
      - php
    depends_on:
      - db
      - php
    tty: true
